version: "3.8"

services:
  my-mongodb:
    image: mongo:latest
    container_name: mongo
    hostname: my-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d
    networks:
      - internal


  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - my-mongodb
    networks:
      - internal

volumes:
  mongodb_data_container:

networks:
  internal:
    driver: bridge




